const fs = require("fs");
const s = fs.readFileSync("src/services/i18n.ts", "utf8");
const zhStart = s.indexOf('"zh-CN": {');
const enStart = s.indexOf("  en: {");
const ifaceStart = s.indexOf("export interface TranslationKeys");
const typedStart = s.indexOf("const typedTranslations");
const zhBlock = s.slice(zhStart, enStart);
const enBlock = s.slice(enStart, ifaceStart);
const iface = s.slice(ifaceStart, typedStart);
const keys = (b) => [...b.matchAll(/^ {4}(\w+)[:(]/gm)].map((m) => m[1]);
const typeKeys = (b) => [...b.matchAll(/^ {2}(\w+)[:(]/gm)].map((m) => m[1]);
const zh = keys(zhBlock), en = keys(enBlock), ty = typeKeys(iface);
const diff = (a, b) => a.filter((x) => !b.includes(x));
console.log("counts", zh.length, en.length, ty.length);
console.log("zh-not-en", diff(zh, en));
console.log("en-not-zh", diff(en, zh));
console.log("zh-not-type", diff(zh, ty));
console.log("type-not-zh", diff(ty, zh));
const dup = (a) => a.filter((x, i) => a.indexOf(x) !== i);
console.log("dups zh", dup(zh), "dups en", dup(en), "dups ty", dup(ty));
